package com.example.user.pojo;

import javax.validation.constraints.Size;

public class User {
    @Override
    public String toString() {
        return "User{" +
                "userid='" + userid + '\'' +
                ", username='" + username + '\'' +
                ", userpassword='" + userpassword + '\'' +
                ", usersignature='" + usersignature + '\'' +
                ", usergrade=" + usergrade +
                ", usergold=" + usergold +
                ", userphoto='" + userphoto + '\'' +
                ", reserved1='" + reserved1 + '\'' +
                ", reserved2='" + reserved2 + '\'' +
                ", reserved3='" + reserved3 + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated
     */

    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userpassword
     *
     * @mbggenerated
     */
    @Size(min = 6 ,max = 12,message = "密码长度在6与12个字符之间!")
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usersignature
     *
     * @mbggenerated
     */
    private String usersignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usergrade
     *
     * @mbggenerated
     */
    private Integer usergrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usergold
     *
     * @mbggenerated
     */
    private Integer usergold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userphoto
     *
     * @mbggenerated
     */
    private String userphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reserved1
     *
     * @mbggenerated
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reserved2
     *
     * @mbggenerated
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reserved3
     *
     * @mbggenerated
     */
    private String reserved3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userpassword
     *
     * @return the value of user.userpassword
     *
     * @mbggenerated
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userpassword
     *
     * @param userpassword the value for user.userpassword
     *
     * @mbggenerated
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usersignature
     *
     * @return the value of user.usersignature
     *
     * @mbggenerated
     */
    public String getUsersignature() {
        return usersignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usersignature
     *
     * @param usersignature the value for user.usersignature
     *
     * @mbggenerated
     */
    public void setUsersignature(String usersignature) {
        this.usersignature = usersignature == null ? null : usersignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usergrade
     *
     * @return the value of user.usergrade
     *
     * @mbggenerated
     */
    public Integer getUsergrade() {
        return usergrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usergrade
     *
     * @param usergrade the value for user.usergrade
     *
     * @mbggenerated
     */
    public void setUsergrade(Integer usergrade) {
        this.usergrade = usergrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usergold
     *
     * @return the value of user.usergold
     *
     * @mbggenerated
     */
    public Integer getUsergold() {
        return usergold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usergold
     *
     * @param usergold the value for user.usergold
     *
     * @mbggenerated
     */
    public void setUsergold(Integer usergold) {
        this.usergold = usergold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userphoto
     *
     * @return the value of user.userphoto
     *
     * @mbggenerated
     */
    public String getUserphoto() {
        return userphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userphoto
     *
     * @param userphoto the value for user.userphoto
     *
     * @mbggenerated
     */
    public void setUserphoto(String userphoto) {
        this.userphoto = userphoto == null ? null : userphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reserved1
     *
     * @return the value of user.reserved1
     *
     * @mbggenerated
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reserved1
     *
     * @param reserved1 the value for user.reserved1
     *
     * @mbggenerated
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reserved2
     *
     * @return the value of user.reserved2
     *
     * @mbggenerated
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reserved2
     *
     * @param reserved2 the value for user.reserved2
     *
     * @mbggenerated
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reserved3
     *
     * @return the value of user.reserved3
     *
     * @mbggenerated
     */
    public String getReserved3() {
        return reserved3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reserved3
     *
     * @param reserved3 the value for user.reserved3
     *
     * @mbggenerated
     */
    public void setReserved3(String reserved3) {
        this.reserved3 = reserved3 == null ? null : reserved3.trim();
    }
}